from fpdf import FPDF
import textwrap
import os

class PDF(FPDF):
    def header(self):
        # Logo or Title
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'KrishiSahay - Agricultural Expert', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def generate_prescription(query, offline_answer, online_answer=None, filename="prescription.pdf"):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Fonts: Arial fits standard ASCII. For India languages, we'd need a UTF-8 font (e.g., NotoSans),
    # but FPDF basic has limits. We'll stick to a clean layout assuming English/Transliterated for safety, 
    # or handle encoding errors gracefully.
    pdf.set_font("Arial", size=12)

    # Question
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Farmer's Query:", ln=True)
    pdf.set_font("Arial", size=12)
    
    # Sanitize and write
    q_safe = query.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 8, q_safe)
    pdf.ln(5)

    # Offline Answer
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Knowledge Base Recommendation:", ln=True)
    pdf.set_font("Arial", size=12)
    
    off_safe = offline_answer.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 8, off_safe)
    pdf.ln(5)

    # Online Answer (if available)
    if online_answer:
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, "AI Expert Advice:", ln=True)
        pdf.set_font("Arial", size=12)
        on_safe = online_answer.encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(0, 8, on_safe)
    
    # Disclaimer
    pdf.ln(10)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 5, "Disclaimer: This advice is generated by AI and verified databases. Please consult a local agricultural officer for critical decisions.")

    # Save
    # In Streamlit Cloud or local, we save to a temp path usually, or directly to bytes. 
    # For now, save to file.
    pdf.output(filename)
    return filename
